name: heroku deployment

on:
  push:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Heroku Action
      uses: CDNievas/heroku-action@v1.0
      with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            # Email from Heroku Account
            heroku_email: ${{secrets.HEROKU_EMAIL}}
            # The appname to use for deploying/updating
            heroku_app_name: ${{secrets.HEROKU_APP}}
