
name: heroku deployment

on:
  push:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # You may pin to the exact commit or the version.
    - name: Deploy to production
      run: |
        git push https://heroku:$HEROKU_API_KEY@git.heroku.com/studomia.git master
